### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by sudhir2016** [IlyasMoutawwakil/py-tgi#5]
Getting this error
ProtocolError                             Traceback (most recent call last)
ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

DockerException                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/docker/api/client.py](https://localhost:8080/#) in _retrieve_server_version(self)
    218             ) from ke
    219         except Exception as e:
--> 220             raise DockerException(
    221                 f'Error while fetching server API version: {e}'
    222             ) from e

DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by IlyasMoutawwakil** [comment]
Hi, do you have docker installed in your machine ?

**Comment by sudhir2016** [comment]
No I tried on Google Colab.

**Comment by IlyasMoutawwakil** [comment]
yeh colab seems to be against using docker on their notebooks, apparently `udocker` can be used but I know it's not great with GPUs

**Comment by sudhir2016** [comment]
Thanks for the feedback.
